using System;

namespace AMI.Domain.Entities
{
    /// <summary>
    /// An entity representing a log entry generated by the application.
    /// </summary>
    public class AuditEventEntity
    {
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or sets the timestamp.
        /// </summary>
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Gets or sets the type of the event.
        /// </summary>
        public int EventType { get; set; }

        /// <summary>
        /// Gets or sets the type of the sub event.
        /// </summary>
        public int SubEventType { get; set; }

        /// <summary>
        /// Gets or sets the serialized event.
        /// </summary>
        public string EventSerialized { get; set; }
    }
}
