using System;

namespace AMI.Domain.Entities
{
    /// <summary>
    /// An entity representing events generated by the application.
    /// </summary>
    public class EventEntity
    {
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or sets the created date.
        /// </summary>
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Gets or sets the modified date.
        /// </summary>
        public DateTime ModifiedDate { get; set; }

        /// <summary>
        /// Gets or sets the API version used to render data.
        /// </summary>
        public string ApiVersion { get; set; }

        /// <summary>
        /// Gets or sets the type of the event.
        /// </summary>
        public int EventType { get; set; }

        /// <summary>
        /// Gets or sets the user identifier that originated the event.
        /// </summary>
        public string UserId { get; set; }

        /// <summary>
        /// Gets or sets the serialized event.
        /// </summary>
        public string EventSerialized { get; set; }
    }
}
