using System;
using AMI.Domain.Entities;

namespace AMI.Core.Entities.Models
{
    /// <summary>
    /// A model representing a log entry generated by the application.
    /// </summary>
    public class AppLogModel
    {
        /// <summary>
        /// Gets or sets the timestamp.
        /// </summary>
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Gets or sets the message.
        /// </summary>
        public string Message { get; set; }

        /// <summary>
        /// Gets or sets the level.
        /// </summary>
        public string Level { get; set; }

        /// <summary>
        /// Gets or sets the exception.
        /// </summary>
        public string Exception { get; set; }

        /// <summary>
        /// Gets or sets the event identifier.
        /// </summary>
        public string EventId { get; set; }

        /// <summary>
        /// Gets or sets the source context.
        /// </summary>
        public string SourceContext { get; set; }

        /// <summary>
        /// Creates a model based on the given domain entity.
        /// </summary>
        /// <param name="entity">The domain entity.</param>
        /// <returns>The domain entity as a model.</returns>
        public static AppLogModel Create(AppLogEntity entity)
        {
            if (entity == null)
            {
                return null;
            }

            var model = new AppLogModel
            {
                Timestamp = entity.Timestamp,
                Message = entity.Message,
                Level = entity.Level,
                Exception = entity.Exception,
                EventId = entity.EventId,
                SourceContext = entity.SourceContext
            };

            return model;
        }
    }
}
