using System.Threading;
using System.Threading.Tasks;
using AMI.Domain.Enums;

namespace AMI.Core.Services
{
    /// <summary>
    /// An interface representing a service for events generated by the application.
    /// </summary>
    public interface IEventService
    {
        /// <summary>
        /// Creates the asynchronous.
        /// </summary>
        /// <typeparam name="T">The type of the data.</typeparam>
        /// <param name="userId">The user identifier.</param>
        /// <param name="eventType">The type of the event.</param>
        /// <param name="data">The event data.</param>
        /// <param name="ct">The cancellation token.</param>
        /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
        Task CreateAsync<T>(string userId, EventType eventType, T data, CancellationToken ct);
    }
}
