using System.Collections.Generic;
using AMI.Core.Repositories;
using AMI.Domain.Entities;

namespace AMI.Infrastructure.Repositories
{
    /// <summary>
    /// A repository for application logs.
    /// </summary>
    public class AppLogRepository : BaseRepository<AppLogEntity>, IAppLogRepository
    {
        private readonly ListRepository<AppLogEntity> repository;

        /// <summary>
        /// Initializes a new instance of the <see cref="AppLogRepository"/> class.
        /// </summary>
        public AppLogRepository()
        {
            // TODO: read the file generated by Serilog
            repository = new ListRepository<AppLogEntity>(new List<AppLogEntity>());
        }

        /// <inheritdoc/>
        protected override IRepository<AppLogEntity> Repository
        {
            get
            {
                return repository;
            }
        }
    }
}
